In [1]:
from theano.sandbox import cuda

Using gpu device 0: Tesla K80 (CNMeM is disabled, cuDNN 5103)
/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)

In [105]:
%matplotlib inline
import utils
from utils import *
import pandas as pd
from keras.layers import Input, Embedding

In [10]:
path = 'data/ml-latest-small/'

In [61]:
df_rating = pd.read_csv(path+'ratings.csv')

In [34]:
df_rating

        userId  movieId  rating   timestamp
0            0       31     2.5  1260759144
1            0     1029     3.0  1260759179
2            0     1061     3.0  1260759182
3            0     1129     2.0  1260759185
4            0     1172     4.0  1260759205
5            0     1263     2.0  1260759151
6            0     1287     2.0  1260759187
7            0     1293     2.0  1260759148
8            0     1339     3.5  1260759125
9            0     1343     2.0  1260759131
10           0     1371     2.5  1260759135
11           0     1405     1.0  1260759203
12           0     1953     4.0  1260759191
13           0     2105     4.0  1260759139
14           0     2150     3.0  1260759194
15           0     2193     2.0  1260759198
16           0     2294     2.0  1260759108
17           0     2455     2.5  1260759113
18           0     2968     1.0  1260759200
19           0     3671     3.0  1260759117
20           1       10     4.0   835355493
21           1       17     5.0   835355681
22           1       39     5.0   835355604
23           1       47     4.0   835355552
24           1       50     4.0   835355586
25           1       52     3.0   835356031
26           1       62     3.0   835355749
27           1      110     4.0   835355532
28           1      144     3.0   835356016
29           1      150     5.0   835355395
...        ...      ...     ...         ...
99974      670     4034     4.5  1064245493
99975      670     4306     5.0  1064245548
99976      670     4308     3.5  1065111985
99977      670     4880     4.0  1065111973
99978      670     4886     5.0  1064245488
99979      670     4896     5.0  1065111996
99980      670     4963     4.5  1065111855
99981      670     4973     4.5  1064245471
99982      670     4993     5.0  1064245483
99983      670     4995     4.0  1064891537
99984      670     5010     2.0  1066793004
99985      670     5218     2.0  1065111990
99986      670     5299     3.0  1065112004
99987      670     5349     4.0  1065111863
99988      670     5377     4.0  1064245557
99989      670     5445     4.5  1064891627
99990      670     5464     3.0  1064891549
99991      670     5669     4.0  1063502711
99992      670     5816     4.0  1065111963
99993      670     5902     3.5  1064245507
99994      670     5952     5.0  1063502716
99995      670     5989     4.0  1064890625
99996      670     5991     4.5  1064245387
99997      670     5995     4.0  1066793014
99998      670     6212     2.5  1065149436
99999      670     6268     2.5  1065579370
100000     670     6269     4.0  1065149201
100001     670     6365     4.0  1070940363
100002     670     6385     2.5  1070979663
100003     670     6565     3.5  1074784724

[100004 rows x 4 columns]

In [15]:
len(df_rating)

100004

In [62]:
users = df_rating.userId.unique()
len(users)

671

In [63]:
movies = df_rating.movieId.unique()

In [65]:
df_rating

        userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
5            1     1263     2.0  1260759151
6            1     1287     2.0  1260759187
7            1     1293     2.0  1260759148
8            1     1339     3.5  1260759125
9            1     1343     2.0  1260759131
10           1     1371     2.5  1260759135
11           1     1405     1.0  1260759203
12           1     1953     4.0  1260759191
13           1     2105     4.0  1260759139
14           1     2150     3.0  1260759194
15           1     2193     2.0  1260759198
16           1     2294     2.0  1260759108
17           1     2455     2.5  1260759113
18           1     2968     1.0  1260759200
19           1     3671     3.0  1260759117
20           2       10     4.0   835355493
21           2       17     5.0   835355681
22           2       39     5.0   835355604
23           2       47     4.0   835355552
24           2       50     4.0   835355586
25           2       52     3.0   835356031
26           2       62     3.0   835355749
27           2      110     4.0   835355532
28           2      144     3.0   835356016
29           2      150     5.0   835355395
...        ...      ...     ...         ...
99974      671     4034     4.5  1064245493
99975      671     4306     5.0  1064245548
99976      671     4308     3.5  1065111985
99977      671     4880     4.0  1065111973
99978      671     4886     5.0  1064245488
99979      671     4896     5.0  1065111996
99980      671     4963     4.5  1065111855
99981      671     4973     4.5  1064245471
99982      671     4993     5.0  1064245483
99983      671     4995     4.0  1064891537
99984      671     5010     2.0  1066793004
99985      671     5218     2.0  1065111990
99986      671     5299     3.0  1065112004
99987      671     5349     4.0  1065111863
99988      671     5377     4.0  1064245557
99989      671     5445     4.5  1064891627
99990      671     5464     3.0  1064891549
99991      671     5669     4.0  1063502711
99992      671     5816     4.0  1065111963
99993      671     5902     3.5  1064245507
99994      671     5952     5.0  1063502716
99995      671     5989     4.0  1064890625
99996      671     5991     4.5  1064245387
99997      671     5995     4.0  1066793014
99998      671     6212     2.5  1065149436
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [66]:
userdIDs = {o:i for i,o in enumerate(users)}
movieIDs = {o:i for i,o in enumerate(movies)}

In [67]:
df_rating.userId = df_rating.userId.apply(lambda x : userdIDs[x])

In [68]:
df_rating.movieId = df_rating.movieId.apply(lambda x : movieIDs[x])

In [ ]:
df_rating.movieId

In [ ]:
df_rating.userId

In [69]:
user_min,user_max,movie_min,movie_max = (df_rating.userId.min(),df_rating.userId.max(),df_rating.movieId.min(), df_rating.movieId.max())
user_min,user_max,movie_min,movie_max

(0, 670, 0, 9065)

In [43]:
n_users = df_rating.userId.nunique()

In [44]:
n_movie = df_rating.movieId.nunique()
n_users,n_movie

(671, 9066)

In [45]:
n_factors = 50

In [46]:
np.random.seed = 42

In [47]:
msk = np.random.rand(len(df_rating))<0.8

In [49]:
trn = df_rating[msk]

In [52]:
msk

array([ True, False,  True, ..., False, False,  True], dtype=bool)

In [75]:
df_rating.head()

   userId  movieId  rating   timestamp
0       0        0     2.5  1260759144
1       0        1     3.0  1260759179
2       0        2     3.0  1260759182
3       0        3     2.0  1260759185
4       0        4     4.0  1260759205

In [79]:
top_user_= df_rating.groupby('userId')['rating'].count()

In [83]:
top_users = top_user_.sort_values(ascending=False)[:15]

In [84]:
top_users

userId
546    2391
563    1868
623    1735
14     1700
72     1610
451    1340
467    1291
379    1063
310    1019
29     1011
293     947
508     923
579     922
212     910
211     876
Name: rating, dtype: int64

In [91]:
top_m  =df_rating.groupby('movieId')['rating'].count()

In [92]:
top_movie = top_m.sort_values(ascending=False)[:15]

In [93]:
top_movie

movieId
57     341
49     324
99     311
92     304
143    291
72     274
402    259
417    247
79     244
89     237
179    234
27     228
197    226
505    224
180    220
Name: rating, dtype: int64

In [96]:
top_r = df_rating.join(top_users,rsuffix='_r',how='inner',on='userId')

In [97]:
top_r = top_r.join(top_movie,rsuffix='_r',how='inner',on='movieId')

In [99]:
a=pd.crosstab(top_r.userId, top_r.movieId,top_r.rating,aggfunc=np.sum)

In [104]:
a.to_csv()

movieId,27,49,57,72,79,89,92,99,143,179,180,197,402,417,505
userId,,,,,,,,,,,,,,,
14,3.0,5.0,1.0,3.0,4.0,4.0,5.0,2.0,5.0,5.0,4.0,5.0,5.0,2.0,5.0
29,5.0,5.0,5.0,4.0,5.0,4.0,4.0,5.0,4.0,4.0,5.0,5.0,3.0,4.0,5.0
72,4.0,5.0,5.0,4.0,5.0,3.0,4.5,5.0,4.5,5.0,5.0,5.0,4.5,5.0,4.0
211,5.0,4.0,4.0,3.0,5.0,3.0,4.0,4.5,4.0,NaN,3.0,3.0,5.0,3.0,NaN
212,2.5,NaN,2.0,5.0,NaN,4.0,2.5,NaN,5.0,5.0,3.0,3.0,4.0,3.0,2.0
293,3.0,NaN,4.0,4.0,4.0,3.0,NaN,3.0,4.0,4.0,4.5,4.0,4.5,4.0,NaN
310,3.0,3.0,5.0,4.5,5.0,4.5,2.0,4.5,4.0,3.0,4.5,4.5,4.0,3.0,4.0
379,5.0,5.0,5.0,4.0,NaN,4.0,5.0,4.0,4.0,4.0,NaN,3.0,5.0,4.0,4.0
451,4.0,5.0,4.0,5.0,4.0,4.0,5.0,5.0,4.0,4.0,4.0,4.0,2.0,3.5,5.0
467,3.0,3.5,3.0,2.5,NaN,NaN,3.0,3.5,3.5,3.0,3.5,3.0,3.0,4.0,4.0
508,5.0,5.0,4.0,3.0,5.0,2.0,4.0,4.0,5.0,5.0,5.0,3.0,4.5,3.0,4.5
546,NaN,5.0,2.0,3.0,5.0,NaN,5.0,5.0,NaN,2.5,2.0,3.5,3.5,3.5,5.0
563,1.0,5.0,3.0,5.0,4.0,5.0,5.0,NaN,2.0,5.0,5.0,3.0,3.0,4.0,5.0
579,4.5,4.5,3.5,3.0,4.0,4.5,4.0,4.0,4.0,4.0,3.5,3.0,4.5,4.0,4.5
623,NaN,5.0,3.0,3.0,NaN,3.0,5.0,NaN,5.0,5.0,5.0,5.0,2.0,5.0,4.0

In [101]:
exxData = 'ex.csv'

In [103]:
FileLink(exxData)

/home/ubuntu/courses/deeplearning1/nbs/ex.csv

In [51]:
val = df_rating[~msk]
val

        userId  movieId  rating   timestamp
1            0        1     3.0  1260759179
6            0        6     2.0  1260759187
10           0       10     2.5  1260759135
18           0       18     1.0  1260759200
25           1       25     3.0   835356031
28           1       28     3.0   835356016
33           1       33     3.0   835355710
36           1       36     3.0   835355511
42           1       42     4.0   835355511
48           1       48     3.0   835355492
54           1       54     3.0   835355492
58           1       58     3.0   835355749
61           1       61     2.0   835355932
66           1       66     2.0   835356246
67           1       67     3.0   835355532
78           1       78     4.0   835355817
82           1       82     3.0   835356109
84           1       84     3.0   835355860
92           1       92     3.0   835355511
95           1       95     4.0   835355978
105          2       79     3.0  1298862528
106          2       88     3.0  1298922100
107          2       91     3.0  1298923247
109          2      101     2.0  1298923260
112          2      104     3.0  1298861687
117          2      109     4.0  1298861658
122          2      114     4.0  1298861753
127          2      119     3.5  1298922057
138          2      130     3.0  1298922065
144          2      136     4.5  1298862467
...        ...      ...     ...         ...
99892      670      684     4.0  1064890230
99896      670       57     5.0  1063503911
99898      670     2529     2.5  1063503739
99900      670      578     4.0  1064891534
99903      670       89     5.0  1064891610
99909      670      170     3.5  1064891601
99917      670      182     3.0  1063500775
99921      670      191     4.0  1064891597
99928      670      828     4.0  1064891635
99932      670      459     4.0  1064890702
99934      670      878     3.5  1063500873
99938      670      517     5.0  1063500850
99940      670      339     4.0  1063500762
99943      670     4823     4.0  1065149286
99944      670      341     3.5  1063503856
99945      670      402     4.5  1064891076
99946      670      281     4.0  1063500751
99949      670      289     4.0  1063500821
99950      670      290     5.0  1064890525
99952      670      298     4.0  1065149106
99955      670      407     1.0  1063503966
99962      670     1028     4.0  1074784735
99966      670      409     4.0  1065111939
99970      670      472     3.5  1065111959
99977      670     5577     4.0  1065111973
99980      670      358     4.5  1065111855
99995      670      486     4.0  1064890625
100000     670     4771     4.0  1065149201
100001     670     1329     4.0  1070940363
100002     670     1331     2.5  1070979663

[20023 rows x 4 columns]

In [16]:
df_movies = pd.read_csv(path +'movies.csv')

In [17]:
df_movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [19]:
len(df_movies)

9125

len(df_movies)

In [18]:
df_links= pd.read_csv(path+'links.csv')
df_links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [107]:
user_in = Input(shape=(1,),dtype='int64',name='user_in')
u = Embedding(n_users,n_factors,input_length=1,W_regularizer=l2(1e-4))(user_in)

In [108]:
movie_in = Input(shape=(1,),dtype='int64',name='movie_in')
m = Embedding(n_movie,n_factors,input_length=1,W_regularizer=l2(1e-4))(movie_in)

In [109]:
x = merge([u,m],mode='dot')
x= Flatten()(x)
model = Model([user_in,movie_in],x)
model.compile(Adam(0.001),loss='mse')

In [112]:
model.fit([trn.userId,trn.movieId],trn.rating,batch_size=64,nb_epoch=6,validation_data=([val.userId,val.movieId],val.rating))

Train on 79981 samples, validate on 20023 samples
Epoch 1/6
79981/79981 [==============================] - 6s - loss: 10.1075 - val_loss: 3.9862
Epoch 2/6
79981/79981 [==============================] - 6s - loss: 3.1787 - val_loss: 2.0465
Epoch 3/6
79981/79981 [==============================] - 6s - loss: 2.4183 - val_loss: 1.6679
Epoch 4/6
79981/79981 [==============================] - 6s - loss: 2.2397 - val_loss: 1.5258
Epoch 5/6
79981/79981 [==============================] - 6s - loss: 2.1668 - val_loss: 1.4737
Epoch 6/6
79981/79981 [==============================] - 6s - loss: 2.1276 - val_loss: 1.4544

## Adding Bias

In [130]:
def create_bias(inp,n_in):
    x= Embedding(n_in,1,input_length=1)(inp)
    return Flatten()(x)

In [ ]:
def create_bias(inp, n_in):
    x = Embedding(n_in, 1, input_length=1)(inp)
    return Flatten()(x)

In [131]:
user_bias = create_bias(user_in,n_users)

In [133]:
movie_bias

Reshape{2}.0

In [132]:
movie_bias = create_bias(movie_in,n_movie)

In [136]:
x = merge([u,m],mode='dot')
x= Flatten()(x)
x = merge([x,user_bias],mode='sum')
x = merge([x,movie_bias],mode='sum')
model = Model([user_in,movie_in],x)
model.compile(Adam(0.001),loss='mse')

In [138]:
model.fit([trn.userId,trn.movieId],trn.rating,batch_size=64,nb_epoch=10,validation_data=([val.userId,val.movieId],val.rating))

Train on 79981 samples, validate on 20023 samples
Epoch 1/10
79981/79981 [==============================] - 6s - loss: 2.9967 - val_loss: 1.8075
Epoch 2/10
79981/79981 [==============================] - 6s - loss: 2.1786 - val_loss: 1.4292
Epoch 3/10
79981/79981 [==============================] - 6s - loss: 1.9322 - val_loss: 1.2904
Epoch 4/10
40000/79981 [==============>...............] - ETA: 2s - loss: 1.7924

KeyboardInterrupt:

In [139]:
model.optimizer.lr = 0.01
model.fit([trn.userId,trn.movieId],trn.rating,batch_size=64,nb_epoch=3,validation_data=([val.userId,val.movieId],val.rating))

Train on 79981 samples, validate on 20023 samples
Epoch 1/3
79981/79981 [==============================] - 6s - loss: 1.7722 - val_loss: 1.2073
Epoch 2/3
79981/79981 [==============================] - 6s - loss: 1.6859 - val_loss: 1.1662
Epoch 3/3
79981/79981 [==============================] - 6s - loss: 1.6119 - val_loss: 1.1343

In [142]:
model.optimizer.lr = 0.0001
model.fit([trn.userId,trn.movieId],trn.rating,batch_size=64,nb_epoch=10,validation_data=([val.userId,val.movieId],val.rating))

Train on 79981 samples, validate on 20023 samples
Epoch 1/10
79981/79981 [==============================] - 6s - loss: 0.7719 - val_loss: 0.8314
Epoch 2/10
79981/79981 [==============================] - 6s - loss: 0.7411 - val_loss: 0.8229
Epoch 3/10
79981/79981 [==============================] - 5s - loss: 0.7134 - val_loss: 0.8157
Epoch 4/10
79981/79981 [==============================] - 5s - loss: 0.6881 - val_loss: 0.8092
Epoch 5/10
79981/79981 [==============================] - 6s - loss: 0.6654 - val_loss: 0.8053
Epoch 6/10
79981/79981 [==============================] - 5s - loss: 0.6454 - val_loss: 0.8010
Epoch 7/10
79981/79981 [==============================] - 5s - loss: 0.6276 - val_loss: 0.7960
Epoch 8/10
79981/79981 [==============================] - 5s - loss: 0.6121 - val_loss: 0.7940
Epoch 9/10
79981/79981 [==============================] - 5s - loss: 0.5989 - val_loss: 0.7920
Epoch 10/10
79981/79981 [==============================] - 5s - loss: 0.5874 - val_loss: 0.7908

# Making Neural Net

In [143]:
x = merge([u,m],mode='concat')
x= Flatten()(x)
x = Dense(100,activation='relu')(x)
x= Dense(1)(x)
model = Model([user_in,movie_in],x)
model.compile(Adam(0.01),loss='mse')

In [145]:
model.fit([trn.userId,trn.movieId],trn.rating,batch_size=64,nb_epoch=3,validation_data=([val.userId,val.movieId],val.rating))

Train on 79981 samples, validate on 20023 samples
Epoch 1/3
79981/79981 [==============================] - 7s - loss: 1.0194 - val_loss: 0.8208
Epoch 2/3
79981/79981 [==============================] - 7s - loss: 0.9880 - val_loss: 0.8190
Epoch 3/3
79981/79981 [==============================] - 7s - loss: 0.9679 - val_loss: 0.8129

In [146]:
model.optimizer.lr = 0.001
model.fit([trn.userId,trn.movieId],trn.rating,batch_size=64,nb_epoch=3,validation_data=([val.userId,val.movieId],val.rating))

Train on 79981 samples, validate on 20023 samples
Epoch 1/3
79981/79981 [==============================] - 7s - loss: 0.9390 - val_loss: 0.8097
Epoch 2/3
79981/79981 [==============================] - 7s - loss: 0.9207 - val_loss: 0.7980
Epoch 3/3
79981/79981 [==============================] - 7s - loss: 0.9057 - val_loss: 0.8046

In [147]:
model.optimizer.lr = 0.0001
model.fit([trn.userId,trn.movieId],trn.rating,batch_size=64,nb_epoch=10,validation_data=([val.userId,val.movieId],val.rating))

Train on 79981 samples, validate on 20023 samples
Epoch 1/10
79981/79981 [==============================] - 7s - loss: 0.8973 - val_loss: 0.7964
Epoch 2/10
79981/79981 [==============================] - 7s - loss: 0.8925 - val_loss: 0.7920
Epoch 3/10
79981/79981 [==============================] - 7s - loss: 0.8797 - val_loss: 0.7933
Epoch 4/10
79981/79981 [==============================] - 7s - loss: 0.8927 - val_loss: 0.7920
Epoch 5/10
79981/79981 [==============================] - 7s - loss: 0.8770 - val_loss: 0.7944
Epoch 6/10
79981/79981 [==============================] - 7s - loss: 0.8771 - val_loss: 0.8082
Epoch 7/10
79981/79981 [==============================] - 7s - loss: 0.8737 - val_loss: 0.7894
Epoch 8/10
79981/79981 [==============================] - 7s - loss: 0.8714 - val_loss: 0.7900
Epoch 9/10
79981/79981 [==============================] - 7s - loss: 0.8664 - val_loss: 0.7890
Epoch 10/10
79981/79981 [==============================] - 7s - loss: 0.8637 - val_loss: 0.7904

### Adding dropout

In [153]:
x = merge([u,m],mode='concat')
x= Flatten()(x)
x = Dropout(0.3)(x)
x = Dense(100,activation='relu')(x)
x=Dropout(0.7)(x)
x= Dense(1)(x)
model_drop = Model([user_in,movie_in],x)
model_drop.compile(Adam(0.001),loss='mse')

In [155]:
model_drop.fit([trn.userId,trn.movieId],trn.rating,batch_size=64,nb_epoch=10,validation_data=([val.userId,val.movieId],val.rating))

Train on 79981 samples, validate on 20023 samples
Epoch 1/10
79981/79981 [==============================] - 7s - loss: 0.8913 - val_loss: 0.7804
Epoch 2/10
79981/79981 [==============================] - 7s - loss: 0.8515 - val_loss: 0.7793
Epoch 3/10
79981/79981 [==============================] - 7s - loss: 0.8240 - val_loss: 0.7795
Epoch 4/10
79981/79981 [==============================] - 7s - loss: 0.8100 - val_loss: 0.7766
Epoch 5/10
79981/79981 [==============================] - 7s - loss: 0.7968 - val_loss: 0.7785
Epoch 6/10
79981/79981 [==============================] - 7s - loss: 0.7916 - val_loss: 0.7768
Epoch 7/10
79981/79981 [==============================] - 7s - loss: 0.7846 - val_loss: 0.7779
Epoch 8/10
79981/79981 [==============================] - 7s - loss: 0.7806 - val_loss: 0.7783
Epoch 9/10
79981/79981 [==============================] - 7s - loss: 0.7774 - val_loss: 0.7797
Epoch 10/10
79981/79981 [==============================] - 7s - loss: 0.7776 - val_loss: 0.7797

In [159]:
model_drop.save_weights(model_path+'nn_withDorp_movielens_val0.7797.h5')

In [158]:
model_path = 'data/mvResults/'

In [156]:
%pwd

u'/home/ubuntu/courses/deeplearning1/nbs'

In [152]:
model_drop.optimizer.lr = 0.0001
model_drop.fit([trn.userId,trn.movieId],trn.rating,batch_size=64,nb_epoch=10,validation_data=([val.userId,val.movieId],val.rating))

Train on 79981 samples, validate on 20023 samples
Epoch 1/10
79981/79981 [==============================] - 7s - loss: 1.2240 - val_loss: 0.8613
Epoch 2/10
79981/79981 [==============================] - 7s - loss: 1.2150 - val_loss: 0.8641
Epoch 3/10
79981/79981 [==============================] - 7s - loss: 1.2068 - val_loss: 0.8714
Epoch 4/10
79981/79981 [==============================] - 7s - loss: 1.1945 - val_loss: 0.8834
Epoch 5/10
79981/79981 [==============================] - 7s - loss: 1.1908 - val_loss: 0.8935
Epoch 6/10
79981/79981 [==============================] - 7s - loss: 1.1811 - val_loss: 0.8611
Epoch 7/10
79981/79981 [==============================] - 7s - loss: 1.1654 - val_loss: 0.8595
Epoch 8/10
79981/79981 [==============================] - 7s - loss: 1.1547 - val_loss: 0.8600
Epoch 9/10
79981/79981 [==============================] - 7s - loss: 1.1485 - val_loss: 0.8595
Epoch 10/10
79981/79981 [==============================] - 7s - loss: 1.1508 - val_loss: 0.8528

In [ ]:
!tar cvfz notebook.tar.gz *

Dense_model_with_dropout_val_66.h5
Dense_model_without_dropout_val_69.h5
From S to statefarm.ipynb
Iceberg Comp Kaggle.ipynb
Might delete half code.ipynb
More_data_data.csv
Moredata.csv
My First Sentiment ANalysis.ipynb
My Lesson 4 notebook.ipynb
My Lesson6.ipynb
NepredictTrainVggConv/
NepredictTrainVggConv/__attrs__
NepredictTrainVggConv/meta/
NepredictTrainVggConv/meta/storage
NepredictTrainVggConv/meta/sizes
NepredictTrainVggConv/data/
NepredictTrainVggConv/data/__2059.blp
NepredictTrainVggConv/data/__2595.blp
NepredictTrainVggConv/data/__1016.blp
NepredictTrainVggConv/data/__282.blp
NepredictTrainVggConv/data/__2626.blp
NepredictTrainVggConv/data/__2473.blp
NepredictTrainVggConv/data/__3505.blp
NepredictTrainVggConv/data/__2993.blp
NepredictTrainVggConv/data/__158.blp
NepredictTrainVggConv/data/__2464.blp
NepredictTrainVggConv/data/__1496.blp
NepredictTrainVggConv/data/__3596.blp
NepredictTrainVggConv/data/__1553.blp
NepredictTrainVggConv/data/__3409.blp
NepredictTrainVggConv/data/__3795.blp
NepredictTrainVggConv/data/__2248.blp
NepredictTrainVggConv/data/__615.blp
NepredictTrainVggConv/data/__984.blp
NepredictTrainVggConv/data/__3580.blp
NepredictTrainVggConv/data/__1909.blp
NepredictTrainVggConv/data/__1060.blp
NepredictTrainVggConv/data/__2547.blp
NepredictTrainVggConv/data/__1170.blp
NepredictTrainVggConv/data/__1311.blp
NepredictTrainVggConv/data/__2026.blp
NepredictTrainVggConv/data/__1149.blp
NepredictTrainVggConv/data/__2378.blp
NepredictTrainVggConv/data/__148.blp
NepredictTrainVggConv/data/__3814.blp
NepredictTrainVggConv/data/__3183.blp
NepredictTrainVggConv/data/__1864.blp
NepredictTrainVggConv/data/__1397.blp
NepredictTrainVggConv/data/__2659.blp
NepredictTrainVggConv/data/__87.blp
NepredictTrainVggConv/data/__352.blp
NepredictTrainVggConv/data/__2847.blp
NepredictTrainVggConv/data/__960.blp
NepredictTrainVggConv/data/__2385.blp
NepredictTrainVggConv/data/__3330.blp
NepredictTrainVggConv/data/__3293.blp
NepredictTrainVggConv/data/__3761.blp
NepredictTrainVggConv/data/__1884.blp
NepredictTrainVggConv/data/__1616.blp
NepredictTrainVggConv/data/__3471.blp
NepredictTrainVggConv/data/__1974.blp
NepredictTrainVggConv/data/__2733.blp
NepredictTrainVggConv/data/__1233.blp
NepredictTrainVggConv/data/__668.blp
NepredictTrainVggConv/data/__2636.blp
NepredictTrainVggConv/data/__2422.blp
NepredictTrainVggConv/data/__3124.blp
NepredictTrainVggConv/data/__1959.blp
NepredictTrainVggConv/data/__526.blp
NepredictTrainVggConv/data/__3379.blp
NepredictTrainVggConv/data/__2390.blp
NepredictTrainVggConv/data/__1187.blp
NepredictTrainVggConv/data/__713.blp
NepredictTrainVggConv/data/__191.blp
NepredictTrainVggConv/data/__1351.blp
NepredictTrainVggConv/data/__1352.blp
NepredictTrainVggConv/data/__3577.blp
NepredictTrainVggConv/data/__522.blp
NepredictTrainVggConv/data/__852.blp
NepredictTrainVggConv/data/__2342.blp
NepredictTrainVggConv/data/__2953.blp
NepredictTrainVggConv/data/__3399.blp
NepredictTrainVggConv/data/__2878.blp
NepredictTrainVggConv/data/__976.blp
NepredictTrainVggConv/data/__1997.blp
NepredictTrainVggConv/data/__3146.blp
NepredictTrainVggConv/data/__1700.blp
NepredictTrainVggConv/data/__3510.blp
NepredictTrainVggConv/data/__1227.blp
NepredictTrainVggConv/data/__2609.blp
NepredictTrainVggConv/data/__1596.blp
NepredictTrainVggConv/data/__3701.blp
NepredictTrainVggConv/data/__1387.blp
NepredictTrainVggConv/data/__3272.blp
NepredictTrainVggConv/data/__402.blp
NepredictTrainVggConv/data/__3345.blp
NepredictTrainVggConv/data/__446.blp
NepredictTrainVggConv/data/__358.blp
NepredictTrainVggConv/data/__3398.blp
NepredictTrainVggConv/data/__1809.blp
NepredictTrainVggConv/data/__703.blp
NepredictTrainVggConv/data/__3658.blp
NepredictTrainVggConv/data/__3880.blp
NepredictTrainVggConv/data/__2838.blp
NepredictTrainVggConv/data/__135.blp
NepredictTrainVggConv/data/__2702.blp
NepredictTrainVggConv/data/__558.blp
NepredictTrainVggConv/data/__1120.blp
NepredictTrainVggConv/data/__1087.blp
NepredictTrainVggConv/data/__1803.blp
NepredictTrainVggConv/data/__2978.blp
NepredictTrainVggConv/data/__1718.blp
NepredictTrainVggConv/data/__2278.blp
NepredictTrainVggConv/data/__2283.blp
NepredictTrainVggConv/data/__616.blp
NepredictTrainVggConv/data/__514.blp
NepredictTrainVggConv/data/__2360.blp
NepredictTrainVggConv/data/__3927.blp
NepredictTrainVggConv/data/__149.blp
NepredictTrainVggConv/data/__4.blp
NepredictTrainVggConv/data/__2121.blp
NepredictTrainVggConv/data/__1501.blp
NepredictTrainVggConv/data/__3423.blp
NepredictTrainVggConv/data/__3391.blp
NepredictTrainVggConv/data/__2837.blp
NepredictTrainVggConv/data/__2226.blp
NepredictTrainVggConv/data/__2830.blp
NepredictTrainVggConv/data/__1655.blp
NepredictTrainVggConv/data/__2337.blp
NepredictTrainVggConv/data/__2138.blp
NepredictTrainVggConv/data/__601.blp
NepredictTrainVggConv/data/__947.blp
NepredictTrainVggConv/data/__1848.blp
NepredictTrainVggConv/data/__867.blp
NepredictTrainVggConv/data/__202.blp
NepredictTrainVggConv/data/__1135.blp
NepredictTrainVggConv/data/__341.blp
NepredictTrainVggConv/data/__1935.blp
NepredictTrainVggConv/data/__1534.blp
NepredictTrainVggConv/data/__596.blp
NepredictTrainVggConv/data/__1741.blp
NepredictTrainVggConv/data/__1329.blp
NepredictTrainVggConv/data/__2205.blp
NepredictTrainVggConv/data/__646.blp
NepredictTrainVggConv/data/__1669.blp
NepredictTrainVggConv/data/__385.blp
NepredictTrainVggConv/data/__2232.blp
NepredictTrainVggConv/data/__771.blp
NepredictTrainVggConv/data/__276.blp
NepredictTrainVggConv/data/__188.blp
NepredictTrainVggConv/data/__4003.blp
NepredictTrainVggConv/data/__697.blp
NepredictTrainVggConv/data/__1547.blp
NepredictTrainVggConv/data/__80.blp
NepredictTrainVggConv/data/__3360.blp
NepredictTrainVggConv/data/__1292.blp
NepredictTrainVggConv/data/__539.blp
NepredictTrainVggConv/data/__485.blp
NepredictTrainVggConv/data/__1337.blp
NepredictTrainVggConv/data/__1868.blp
NepredictTrainVggConv/data/__2313.blp
NepredictTrainVggConv/data/__4004.blp
NepredictTrainVggConv/data/__1208.blp
NepredictTrainVggConv/data/__3274.blp
NepredictTrainVggConv/data/__2317.blp
NepredictTrainVggConv/data/__2881.blp
NepredictTrainVggConv/data/__3692.blp
NepredictTrainVggConv/data/__2132.blp
NepredictTrainVggConv/data/__775.blp
NepredictTrainVggConv/data/__2678.blp
NepredictTrainVggConv/data/__2946.blp
NepredictTrainVggConv/data/__2956.blp
NepredictTrainVggConv/data/__3615.blp
NepredictTrainVggConv/data/__1859.blp
NepredictTrainVggConv/data/__2215.blp
NepredictTrainVggConv/data/__1359.blp
NepredictTrainVggConv/data/__2517.blp
NepredictTrainVggConv/data/__2655.blp
NepredictTrainVggConv/data/__1767.blp
NepredictTrainVggConv/data/__1036.blp
NepredictTrainVggConv/data/__11.blp
NepredictTrainVggConv/data/__2937.blp
NepredictTrainVggConv/data/__1027.blp
NepredictTrainVggConv/data/__856.blp
NepredictTrainVggConv/data/__923.blp
NepredictTrainVggConv/data/__2420.blp
NepredictTrainVggConv/data/__2137.blp
NepredictTrainVggConv/data/__1180.blp
NepredictTrainVggConv/data/__1818.blp
NepredictTrainVggConv/data/__3166.blp
NepredictTrainVggConv/data/__3200.blp
NepredictTrainVggConv/data/__3222.blp
NepredictTrainVggConv/data/__1846.blp
NepredictTrainVggConv/data/__3515.blp
NepredictTrainVggConv/data/__3232.blp
NepredictTrainVggConv/data/__3700.blp
NepredictTrainVggConv/data/__2909.blp
NepredictTrainVggConv/data/__2368.blp
NepredictTrainVggConv/data/__3080.blp
NepredictTrainVggConv/data/__698.blp
NepredictTrainVggConv/data/__1134.blp
NepredictTrainVggConv/data/__939.blp
NepredictTrainVggConv/data/__174.blp
NepredictTrainVggConv/data/__1536.blp
NepredictTrainVggConv/data/__4046.blp
NepredictTrainVggConv/data/__888.blp
NepredictTrainVggConv/data/__3999.blp
NepredictTrainVggConv/data/__1542.blp
NepredictTrainVggConv/data/__3570.blp
NepredictTrainVggConv/data/__1644.blp
NepredictTrainVggConv/data/__209.blp
NepredictTrainVggConv/data/__3078.blp
NepredictTrainVggConv/data/__989.blp
NepredictTrainVggConv/data/__3038.blp
NepredictTrainVggConv/data/__1480.blp
NepredictTrainVggConv/data/__1625.blp
NepredictTrainVggConv/data/__2108.blp
NepredictTrainVggConv/data/__3831.blp
NepredictTrainVggConv/data/__2552.blp
NepredictTrainVggConv/data/__1532.blp
NepredictTrainVggConv/data/__968.blp
NepredictTrainVggConv/data/__1421.blp
NepredictTrainVggConv/data/__140.blp
NepredictTrainVggConv/data/__2201.blp
NepredictTrainVggConv/data/__3264.blp
NepredictTrainVggConv/data/__2960.blp
NepredictTrainVggConv/data/__365.blp
NepredictTrainVggConv/data/__360.blp
NepredictTrainVggConv/data/__1319.blp
NepredictTrainVggConv/data/__2174.blp
NepredictTrainVggConv/data/__2319.blp
NepredictTrainVggConv/data/__568.blp
NepredictTrainVggConv/data/__878.blp
NepredictTrainVggConv/data/__3134.blp
NepredictTrainVggConv/data/__686.blp
NepredictTrainVggConv/data/__215.blp
NepredictTrainVggConv/data/__1766.blp
NepredictTrainVggConv/data/__815.blp
NepredictTrainVggConv/data/__1221.blp
NepredictTrainVggConv/data/__77.blp
NepredictTrainVggConv/data/__1477.blp
NepredictTrainVggConv/data/__3156.blp